### ISSUE TITLE
☑️ Publishing QA Checklist

### ISSUE THREAD

**Issue by jacqui** [news-catalyst/google-app-scripts#347]
What to check to verify the sidebar is working:

**Articles:**

- [ ] preview an existing article
- [ ] click preview link to view preview version of article
- [ ] publish an existing article without a source
- [ ] click publish link to view published version of article
- [ ] publish an existing article with a source
- [ ] add more than one source to an article
- [ ] update tags on an article, check these are preserved
- [ ] update author(s) on an article, check it's preserved
- [ ] create new doc ➡ create new test case ➡ set slug & category & locale to existing article values ➡ try to preview ➡ should get error
- [ ] create new doc ➡ create new test case ➡ set slug & category & locale to existing article values ➡ try to publish ➡ should get error
- [ ] click to create a new translation on existing article
- [ ] click to open existing translation in article

**Pages:**

- [ ] preview an existing page
- [ ] click link to view preview version of page
- [ ] publish an existing page
- [ ] click link to view published version of page
- [ ] create new doc ➡ create new test case ➡ set slug & locale to existing page values ➡ try to preview ➡ should get error
- [ ] create new doc  ➡ create new test case ➡ set slug & locale to existing page values  ➡ try to publish  ➡ should get error
- [ ] change slug in new doc  ➡ then preview  ➡ should succeed
- [ ] new doc with changed slug  ➡ should also publish successfully
- [ ] click to create a new translation on existing page
- [ ] click to open existing translation in page
